# Generated by Django 5.0.2 on 2024-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_rt',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_rt',
            name='tprice',
            field=models.IntegerField(),
        ),
    ]
