# Generated by Django 5.0.2 on 2024-02-16 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_c_rt_price_alter_c_rt_tprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.ImageField(upload_to='images/profilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.join')),
            ],
        ),
    ]
