# Generated by Django 5.0.2 on 2024-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='biodata',
            field=models.ImageField(default=1, upload_to='images/profilepic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepic',
            name='license',
            field=models.ImageField(default=1, upload_to='images/profilepic'),
            preserve_default=False,
        ),
    ]
