# Generated by Django 5.0.2 on 2024-02-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_profilepic_biodata_profilepic_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='biodata',
            field=models.FileField(upload_to='images/profilepic'),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='license',
            field=models.FileField(upload_to='images/profilepic'),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='propic',
            field=models.FileField(upload_to='images/profilepic'),
        ),
    ]
