# Generated by Django 5.0.2 on 2024-02-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_profilepic_biodata_alter_profilepic_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='biodata',
        ),
        migrations.RemoveField(
            model_name='profilepic',
            name='license',
        ),
    ]
