# Generated by Django 5.0.2 on 2024-02-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_product_siglebooking_item_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processed', 'Order Processed'), ('Order Dispatched', 'Order Dispatched'), ('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='pending', max_length=150),
        ),
    ]
