# Generated by Django 5.0.2 on 2024-02-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilepic_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic', models.FileField(upload_to='images/profilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.join')),
            ],
        ),
    ]
