# Generated by Django 5.0.2 on 2024-02-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_profilepic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.reg'),
        ),
    ]
