# Generated by Django 5.0.2 on 2024-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_profilepic_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
