# Generated by Django 5.0.2 on 2024-03-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_products_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propic1', models.FileField(upload_to='images/profilepic')),
                ('propic2', models.FileField(upload_to='images/profilepic')),
                ('propic3', models.FileField(upload_to='images/profilepic')),
                ('propic4', models.FileField(upload_to='images/profilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.reg')),
            ],
        ),
    ]
